### PR TITLE
Make NativeAOT work on .NET 8.0

### LINKED ISSUE #2598: YarpOutputCachePolicyProvider breaks AOT compilation in 2.2.0
### Describe the bug
I just updated to 2.2.0 and while validating my proxy I get an exception during startup caused by `YarpOutputCachePolicyProvider`, probably because it is using reflection and it's trying access code that is trimmed away. I'm not even using output caching.

Here's the relevant part of the stack trace:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Reflection.DynamicInvokeInfo..ctor(MethodBase, IntPtr) + 0x314
   at Internal.Reflection.Execution.ExecutionEnvironmentImplementation.TryGetMethodInvokeInfo(RuntimeTypeHandle, QMethodDefinition, RuntimeTypeHandle[], MethodBase, MethodSignatureComparer&, CanonicalFormKind) + 0x191
   at Internal.Reflection.Execution.ExecutionEnvironmentImplementation.TryGetMethodInvoker(RuntimeTypeHandle, QMethodDefinition, RuntimeTypeHandle[]) + 0xe3
   at Internal.Reflection.Core.Execution.ExecutionEnvironment.GetMethodInvoker(RuntimeTypeInfo, QMethodDefinition, RuntimeTypeInfo[], MemberInfo, Exception&) + 0x11e
   at System.Reflection.Runtime.MethodInfos.NativeFormat.NativeFormatMethodCommon.GetUncachedMethodInvoker(RuntimeTypeInfo[], MemberInfo, Exception&) + 0x50
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[], MemberInfo) + 0x1b
   at System.Reflection.Runtime.PropertyInfos.RuntimePropertyInfo.GetValue(Object, BindingFlags, Binder, Object[], CultureInfo) + 0x54
   at System.Reflection.PropertyInfo.GetValue(Object, Object[]) + 0x1d
   at Yarp.ReverseProxy.Configuration.YarpOutputCachePolicyProvider..ctor(IOptions`1 outputCacheOptions) + 0xa7
```

Here is what I think the offending code is:
https://github.com/microsoft/reverse-proxy/blob/99ce21a64e2115f9887e99025ebd2cc2a098d656/src/ReverseProxy/Configuration/IYarpOutputCachePolicyProvider.cs#L35-L37

### To Reproduce
Publish using `PublishAot` and attempt to run the application.

### Potential fix
You might be able to use the `UnsafeAccessorAttribute` in .NET 8:
```csharp
// Define an unsafe accessor
[UnsafeAccessor(UnsafeAccessorKind.Method, Name = "get_NamedPolicies")]
private static extern Dictionary<string, IOutputCachePolicy>? GetNamedPolicies(OutputCacheOptions c);

// Then use it like this
_policyMap = GetNamedPolicies(_outputCacheOptions);
```

For older versions of .NET you need to make sure that the code you are trying to use isn't being trimmed, one way I've successfully done this in my own projects is to create an unused field that references the type with the `DynamicallyAccessedMembersAttribute` stating what I need to keep.
```csharp
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
private static readonly Type keepOutputCacheOptions = typeof(OutputCacheOptions);
```

### Further technical details
- Version 2.2.0
- Windows

### PR DESCRIPTION
**Pull request by MihaZupan**
Adds a workaround to make .NET 8 work.

Closes #2598

### CODE REVIEW

**Review by adityamandaleeka — APPROVED** [review]

File: src/ReverseProxy/Configuration/IYarpOutputCachePolicyProvider.cs [hunk 1]
```diff
@@ -24,6 +25,10 @@ internal interface IYarpOutputCachePolicyProvider
 internal sealed class YarpOutputCachePolicyProvider : IYarpOutputCachePolicyProvider
 {
 #if NET7_0_OR_GREATER
+    // Workaround for https://github.com/dotnet/yarp/issues/2598 to make YARP work with NativeAOT on .NET 8.
```
Comment (adityamandaleeka) [inline src/ReverseProxy/Configuration/IYarpOutputCachePolicyProvider.cs:28]:
```suggestion
    // Workaround for https://github.com/dotnet/yarp/issues/2598 to make YARP work with NativeAOT on .NET 8. This is not needed on .NET 9+.
```
