### PR TITLE
Use exception throw helper

### LINKED ISSUE #2902: Use exception throw helper
Since we're on .NET 8, maybe we could use the exception throw helper from the framework to simplify the exception throw

For example:

Use `ArgumentNullException.ThrowIfNull(context);` to simplify the null checking

before:
```c#
if (context is null)
{
    throw new ArgumentNullException(nameof(context));
}
```

after:

```c#
ArgumentNullException.ThrowIfNull(context);
```

Use `ArgumentException.ThrowIfNullOrEmpty` to simplify the `string.IsNullOrEmpty` checking

before:

```c#
if (string.IsNullOrEmpty(headerName))
{
    throw new ArgumentException($"'{nameof(headerName)}' cannot be null or empty.", nameof(headerName));
}
```

after:

```c#
ArgumentException.ThrowIfNullOrEmpty(headerName);
```

> maybe copilot could help on this

### PR DESCRIPTION
**Pull request by WeihanLi**
- use `ArgumentNullException.ThrowIfNull`
- use `ArgumentException.ThrowIfNullOrEmpty`

fixes #2902

### CODE REVIEW

File: src/ReverseProxy/Forwarder/HttpForwarder.cs [hunk 1]
```diff
@@ -98,11 +101,16 @@ public async ValueTask<ForwarderError> SendAsync(
...
+        ArgumentNullException.ThrowIfNull(context);
+        
+        ArgumentNullException.ThrowIfNull(destinationPrefix);
+        
+        ArgumentNullException.ThrowIfNull(httpClient);
+        
+        ArgumentNullException.ThrowIfNull(requestConfig);
+        
+        ArgumentNullException.ThrowIfNull(transformer);
+
```
Comment (MihaZupan) [inline src/ReverseProxy/Forwarder/HttpForwarder.cs:113]:
```suggestion
        ArgumentNullException.ThrowIfNull(context);
        ArgumentNullException.ThrowIfNull(destinationPrefix);
        ArgumentNullException.ThrowIfNull(httpClient);
        ArgumentNullException.ThrowIfNull(requestConfig);
        ArgumentNullException.ThrowIfNull(transformer);
```

File: src/ReverseProxy/Forwarder/StreamCopier.cs [hunk 2]
```diff
@@ -159,7 +159,8 @@ private sealed class StreamCopierTelemetry
         public StreamCopierTelemetry(bool isRequest, TimeProvider timeProvider)
         {
             _isRequest = isRequest;
-            _timeProvider = timeProvider ?? throw new ArgumentNullException(nameof(timeProvider));
+            ArgumentNullException.ThrowIfNull(timeProvider);
+            _timeProvider = timeProvider;
```
Comment (MihaZupan) [inline src/ReverseProxy/Forwarder/StreamCopier.cs:163]:
```suggestion
            ArgumentNullException.ThrowIfNull(timeProvider);

            _isRequest = isRequest;
            _timeProvider = timeProvider;
```

File: src/ReverseProxy/Forwarder/StreamCopyHttpContent.cs [hunk 3]
```diff
@@ -54,9 +54,11 @@ internal sealed class StreamCopyHttpContent : HttpContent
 
     public StreamCopyHttpContent(HttpContext context, bool isStreamingRequest, TimeProvider timeProvider, ILogger logger, ActivityCancellationTokenSource activityToken)
     {
-        _context = context ?? throw new ArgumentNullException(nameof(context));
+        ArgumentNullException.ThrowIfNull(context);
+        _context = context;
         _isStreamingRequest = isStreamingRequest;
-        _timeProvider = timeProvider ?? throw new ArgumentNullException(nameof(timeProvider));
+        ArgumentNullException.ThrowIfNull(timeProvider);
+        _timeProvider = timeProvider;
```
Comment (MihaZupan) [inline src/ReverseProxy/Forwarder/StreamCopyHttpContent.cs:61]:
```suggestion
        ArgumentNullException.ThrowIfNull(context);
        ArgumentNullException.ThrowIfNull(timeProvider);

        _context = context;
        _isStreamingRequest = isStreamingRequest;
        _timeProvider = timeProvider;
```

File: src/ReverseProxy/Health/DestinationHealthUpdater.cs [hunk 4]
```diff
@@ -22,8 +22,10 @@ public DestinationHealthUpdater(
         ILogger<DestinationHealthUpdater> logger)
     {
         _scheduler = new EntityActionScheduler<(ClusterState Cluster, DestinationState Destination)>(d => Reactivate(d.Cluster, d.Destination), autoStart: true, runOnce: true, timeProvider);
-        _clusterUpdater = clusterDestinationsUpdater ?? throw new ArgumentNullException(nameof(clusterDestinationsUpdater));
-        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
+        ArgumentNullException.ThrowIfNull(clusterDestinationsUpdater);
+        ArgumentNullException.ThrowIfNull(logger);
+        _clusterUpdater = clusterDestinationsUpdater;
+        _logger = logger;
```
Comment (MihaZupan) [inline src/ReverseProxy/Health/DestinationHealthUpdater.cs:28]:
```suggestion
        ArgumentNullException.ThrowIfNull(clusterDestinationsUpdater);
        ArgumentNullException.ThrowIfNull(logger);

        _scheduler = new EntityActionScheduler<(ClusterState Cluster, DestinationState Destination)>(d => Reactivate(d.Cluster, d.Destination), autoStart: true, runOnce: true, timeProvider);
        _clusterUpdater = clusterDestinationsUpdater;
        _logger = logger;
```

File: src/ReverseProxy/Health/EntityActionScheduler.cs [hunk 5]
```diff
@@ -37,9 +37,11 @@ internal sealed class EntityActionScheduler<T> : IDisposable where T : notnull
 
     public EntityActionScheduler(Func<T, Task> action, bool autoStart, bool runOnce, TimeProvider timeProvider)
     {
-        _action = action ?? throw new ArgumentNullException(nameof(action));
+        ArgumentNullException.ThrowIfNull(action);
+        _action = action;
         _runOnce = runOnce;
-        _timeProvider = timeProvider ?? throw new ArgumentNullException(nameof(timeProvider));
+        ArgumentNullException.ThrowIfNull(timeProvider);
+        _timeProvider = timeProvider;
```
Comment (MihaZupan) [inline src/ReverseProxy/Health/EntityActionScheduler.cs:44]:
```suggestion
        ArgumentNullException.ThrowIfNull(action);
        ArgumentNullException.ThrowIfNull(timeProvider);

        _action = action;
        _runOnce = runOnce;
        _timeProvider = timeProvider;
```

File: src/ReverseProxy/Limits/LimitsMiddleware.cs [hunk 6]
```diff
@@ -22,14 +22,17 @@ internal sealed class LimitsMiddleware
 
     public LimitsMiddleware(RequestDelegate next, ILogger<LimitsMiddleware> logger)
     {
-        _next = next ?? throw new ArgumentNullException(nameof(next));
-        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
+        ArgumentNullException.ThrowIfNull(next);
+        _next = next;
+        ArgumentNullException.ThrowIfNull(logger);
+        _logger = logger;
```
Comment (MihaZupan) [inline src/ReverseProxy/Limits/LimitsMiddleware.cs:28]:
```suggestion
        ArgumentNullException.ThrowIfNull(next);
        ArgumentNullException.ThrowIfNull(logger);

        _next = next;
        _logger = logger;
```

File: src/ReverseProxy/Limits/LimitsMiddleware.cs [hunk 7]
```diff
@@ -22,14 +22,17 @@ internal sealed class LimitsMiddleware
...
     }
 
     /// <inheritdoc/>
     public Task Invoke(HttpContext context)
     {
-        _ = context ?? throw new ArgumentNullException(nameof(context));
+        ArgumentNullException.ThrowIfNull(context);
+
```
Comment (MihaZupan) [inline src/ReverseProxy/Limits/LimitsMiddleware.cs:35]:
```suggestion
```

File: src/ReverseProxy/Management/ProxyConfigManager.cs [hunk 8]
```diff
@@ -72,18 +72,30 @@ public ProxyConfigManager(
...
-            ?? clusterChangeListeners?.ToArray() ?? throw new ArgumentNullException(nameof(clusterChangeListeners));
-        _filters = (filters as IProxyConfigFilter[]) ?? filters?.ToArray() ?? throw new ArgumentNullException(nameof(filters));
-        _configValidator = configValidator ?? throw new ArgumentNullException(nameof(configValidator));
-        _proxyEndpointFactory = proxyEndpointFactory ?? throw new ArgumentNullException(nameof(proxyEndpointFactory));
-        _transformBuilder = transformBuilder ?? throw new ArgumentNullException(nameof(transformBuilder));
-        _httpClientFactory = httpClientFactory ?? throw new ArgumentNullException(nameof(httpClientFactory));
-        _activeHealthCheckMonitor = activeHealthCheckMonitor ?? throw new ArgumentNullException(nameof(activeHealthCheckMonitor));
-        _clusterDestinationsUpdater = clusterDestinationsUpdater ?? throw new ArgumentNullException(nameof(clusterDestinationsUpdater));
-        _destinationResolver = destinationResolver ?? throw new ArgumentNullException(nameof(destinationResolver));
+            ?? clusterChangeListeners.ToArray();
```
Comment (MihaZupan) [inline src/ReverseProxy/Management/ProxyConfigManager.cs:90]:
```suggestion
        _clusterChangeListeners = clusterChangeListeners.ToArray();
```

File: src/ReverseProxy/Model/ClusterDestinationsState.cs [hunk 9]
```diff
@@ -12,8 +12,10 @@ public ClusterDestinationsState(
         IReadOnlyList<DestinationState> allDestinations,
         IReadOnlyList<DestinationState> availableDestinations)
     {
-        AllDestinations = allDestinations ?? throw new ArgumentNullException(nameof(allDestinations));
-        AvailableDestinations = availableDestinations ?? throw new ArgumentNullException(nameof(availableDestinations));
+        ArgumentNullException.ThrowIfNull(allDestinations);
+        AllDestinations = allDestinations;
+        ArgumentNullException.ThrowIfNull(availableDestinations);
+        AvailableDestinations = availableDestinations;
```
Comment (MihaZupan) [inline src/ReverseProxy/Model/ClusterDestinationsState.cs:18]:
```suggestion
        ArgumentNullException.ThrowIfNull(allDestinations);
        ArgumentNullException.ThrowIfNull(availableDestinations);

        AllDestinations = allDestinations;
        AvailableDestinations = availableDestinations;
```

File: src/ReverseProxy/Model/ClusterModel.cs [hunk 10]
```diff
@@ -26,8 +26,10 @@ public ClusterModel(
         ClusterConfig config,
         HttpMessageInvoker httpClient)
     {
-        Config = config ?? throw new ArgumentNullException(nameof(config));
-        HttpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
+        ArgumentNullException.ThrowIfNull(config);
+        Config = config;
+        ArgumentNullException.ThrowIfNull(httpClient);
+        HttpClient = httpClient;
```
Comment (MihaZupan) [inline src/ReverseProxy/Model/ClusterModel.cs:32]:
```suggestion
        ArgumentNullException.ThrowIfNull(config);
        ArgumentNullException.ThrowIfNull(httpClient);

        Config = config;
        HttpClient = httpClient;
```

File: src/ReverseProxy/Model/ProxyPipelineInitializerMiddleware.cs [hunk 11]
```diff
@@ -24,10 +24,14 @@ internal sealed class ProxyPipelineInitializerMiddleware
...
-        _next = next ?? throw new ArgumentNullException(nameof(next));
+        ArgumentNullException.ThrowIfNull(logger);
+        _logger = logger;
+        ArgumentNullException.ThrowIfNull(next);
+        _next = next;
 
-        _timeoutOptions = timeoutOptions ?? throw new ArgumentNullException(nameof(timeoutOptions));
+        ArgumentNullException.ThrowIfNull(timeoutOptions);
+
+        _timeoutOptions = timeoutOptions;
```
Comment (MihaZupan) [inline src/ReverseProxy/Model/ProxyPipelineInitializerMiddleware.cs:34]:
```suggestion
        ArgumentNullException.ThrowIfNull(logger);
        ArgumentNullException.ThrowIfNull(next);
        ArgumentNullException.ThrowIfNull(timeoutOptions);

        _logger = logger;
        _next = next;
        _timeoutOptions = timeoutOptions;
```

File: src/ReverseProxy/Model/RouteModel.cs [hunk 12]
```diff
@@ -26,9 +26,11 @@ public RouteModel(
         ClusterState? cluster,
         HttpTransformer transformer)
     {
-        Config = config ?? throw new ArgumentNullException(nameof(config));
+        ArgumentNullException.ThrowIfNull(config);
+        Config = config;
         Cluster = cluster;
-        Transformer = transformer ?? throw new ArgumentNullException(nameof(transformer));
+        ArgumentNullException.ThrowIfNull(transformer);
+        Transformer = transformer;
```
Comment (MihaZupan) [inline src/ReverseProxy/Model/RouteModel.cs:33]:
```suggestion
        ArgumentNullException.ThrowIfNull(config);
        ArgumentNullException.ThrowIfNull(transformer);

        Config = config;
        Cluster = cluster;
        Transformer = transformer;
```

File: src/ReverseProxy/Routing/HeaderMatcherPolicy.cs [hunk 13]
```diff
@@ -26,7 +26,8 @@ internal sealed class HeaderMatcherPolicy : MatcherPolicy, IEndpointComparerPoli
     /// <inheritdoc/>
     bool IEndpointSelectorPolicy.AppliesToEndpoints(IReadOnlyList<Endpoint> endpoints)
     {
-        _ = endpoints ?? throw new ArgumentNullException(nameof(endpoints));
+        ArgumentNullException.ThrowIfNull(endpoints);
+
```
Comment (MihaZupan) [inline src/ReverseProxy/Routing/HeaderMatcherPolicy.cs:30]:
```suggestion
```

File: src/ReverseProxy/Routing/HeaderMatcherPolicy.cs [hunk 14]
```diff
@@ -49,8 +50,10 @@ private static bool AppliesToEndpointsCore(IReadOnlyList<Endpoint> endpoints)
     /// <inheritdoc/>
     public Task ApplyAsync(HttpContext httpContext, CandidateSet candidates)
     {
-        _ = httpContext ?? throw new ArgumentNullException(nameof(httpContext));
-        _ = candidates ?? throw new ArgumentNullException(nameof(candidates));
+        ArgumentNullException.ThrowIfNull(httpContext);
+        
+        ArgumentNullException.ThrowIfNull(candidates);
+
```
Comment (MihaZupan) [inline src/ReverseProxy/Routing/HeaderMatcherPolicy.cs:56]:
```suggestion
        ArgumentNullException.ThrowIfNull(httpContext);
        ArgumentNullException.ThrowIfNull(candidates);
```

File: src/ReverseProxy/Routing/QueryParameterMatcherPolicy.cs [hunk 15]
```diff
@@ -25,7 +25,8 @@ internal sealed class QueryParameterMatcherPolicy : MatcherPolicy, IEndpointComp
     /// <inheritdoc/>
     bool IEndpointSelectorPolicy.AppliesToEndpoints(IReadOnlyList<Endpoint> endpoints)
     {
-        _ = endpoints ?? throw new ArgumentNullException(nameof(endpoints));
+        ArgumentNullException.ThrowIfNull(endpoints);
+
```
Comment (MihaZupan) [inline src/ReverseProxy/Routing/QueryParameterMatcherPolicy.cs:29]:
```suggestion
```

File: src/ReverseProxy/Routing/QueryParameterMatcherPolicy.cs [hunk 16]
```diff
@@ -48,8 +49,10 @@ private static bool AppliesToEndpointsCore(IReadOnlyList<Endpoint> endpoints)
     /// <inheritdoc/>
     public Task ApplyAsync(HttpContext httpContext, CandidateSet candidates)
     {
-        _ = httpContext ?? throw new ArgumentNullException(nameof(httpContext));
-        _ = candidates ?? throw new ArgumentNullException(nameof(candidates));
+        ArgumentNullException.ThrowIfNull(httpContext);
+        
+        ArgumentNullException.ThrowIfNull(candidates);
+
```
Comment (MihaZupan) [inline src/ReverseProxy/Routing/QueryParameterMatcherPolicy.cs:55]:
```suggestion
        ArgumentNullException.ThrowIfNull(httpContext);
        ArgumentNullException.ThrowIfNull(candidates);
```

File: src/ReverseProxy/Routing/ReverseProxyConventionBuilder.cs [hunk 17]
```diff
@@ -24,7 +25,8 @@ internal ReverseProxyConventionBuilder(List<Action<EndpointBuilder>> conventions
     /// <param name="convention">The convention to add to the builder.</param>
     public void Add(Action<EndpointBuilder> convention)
     {
-        _ = convention ?? throw new ArgumentNullException(nameof(convention));
+        ArgumentNullException.ThrowIfNull(convention);
+
```
Comment (MihaZupan) [inline src/ReverseProxy/Routing/ReverseProxyConventionBuilder.cs:29]:
```suggestion
```

File: src/ReverseProxy/Routing/ReverseProxyConventionBuilder.cs [hunk 18]
```diff
@@ -36,7 +38,8 @@ public void Add(Action<EndpointBuilder> convention)
     /// <returns></returns>
     public ReverseProxyConventionBuilder ConfigureEndpoints(Action<IEndpointConventionBuilder> convention)
     {
-        _ = convention ?? throw new ArgumentNullException(nameof(convention));
+        ArgumentNullException.ThrowIfNull(convention);
+
```
Comment (MihaZupan) [inline src/ReverseProxy/Routing/ReverseProxyConventionBuilder.cs:42]:
```suggestion
```

File: src/ReverseProxy/Routing/ReverseProxyConventionBuilder.cs [hunk 19]
```diff
@@ -56,7 +59,8 @@ void Action(EndpointBuilder endpointBuilder)
     /// <returns></returns>
     public ReverseProxyConventionBuilder ConfigureEndpoints(Action<IEndpointConventionBuilder, RouteConfig> convention)
     {
-        _ = convention ?? throw new ArgumentNullException(nameof(convention));
+        ArgumentNullException.ThrowIfNull(convention);
+
```
Comment (MihaZupan) [inline src/ReverseProxy/Routing/ReverseProxyConventionBuilder.cs:63]:
```suggestion
```

File: src/ReverseProxy/Routing/ReverseProxyConventionBuilder.cs [hunk 20]
```diff
@@ -77,7 +81,8 @@ void Action(EndpointBuilder endpointBuilder)
     /// <returns></returns>
     public ReverseProxyConventionBuilder ConfigureEndpoints(Action<IEndpointConventionBuilder, RouteConfig, ClusterConfig?> convention)
     {
-        _ = convention ?? throw new ArgumentNullException(nameof(convention));
+        ArgumentNullException.ThrowIfNull(convention);
+
```
Comment (MihaZupan) [inline src/ReverseProxy/Routing/ReverseProxyConventionBuilder.cs:85]:
```suggestion
```

File: src/ReverseProxy/SessionAffinity/BaseEncryptedSessionAffinityPolicy.cs [hunk 21]
```diff
@@ -20,8 +20,10 @@ internal abstract class BaseEncryptedSessionAffinityPolicy<T> : ISessionAffinity
 
     protected BaseEncryptedSessionAffinityPolicy(IDataProtectionProvider dataProtectionProvider, ILogger logger)
     {
-        _dataProtector = dataProtectionProvider?.CreateProtector(GetType().FullName!) ?? throw new ArgumentNullException(nameof(dataProtectionProvider));
-        Logger = logger ?? throw new ArgumentNullException(nameof(logger));
+        ArgumentNullException.ThrowIfNull(logger);
+        _dataProtector = dataProtectionProvider?.CreateProtector(GetType().FullName!)
+                         ?? throw new ArgumentNullException(nameof(dataProtectionProvider));
+        Logger = logger;
```
Comment (MihaZupan) [inline src/ReverseProxy/SessionAffinity/BaseEncryptedSessionAffinityPolicy.cs:26]:
```suggestion
        ArgumentNullException.ThrowIfNull(logger);
        _dataProtector = dataProtectionProvider?.CreateProtector(GetType().FullName!) ?? throw new ArgumentNullException(nameof(dataProtectionProvider));
        Logger = logger;
```

File: src/ReverseProxy/SessionAffinity/BaseHashCookieSessionAffinityPolicy.cs [hunk 22]
```diff
@@ -18,8 +18,10 @@ internal abstract class BaseHashCookieSessionAffinityPolicy : ISessionAffinityPo
 
     public BaseHashCookieSessionAffinityPolicy(TimeProvider timeProvider, ILogger logger)
     {
-        _timeProvider = timeProvider ?? throw new ArgumentNullException(nameof(timeProvider));
-        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
+        ArgumentNullException.ThrowIfNull(timeProvider);
+        _timeProvider = timeProvider;
+        ArgumentNullException.ThrowIfNull(logger);
+        _logger = logger;
```
Comment (MihaZupan) [inline src/ReverseProxy/SessionAffinity/BaseHashCookieSessionAffinityPolicy.cs:24]:
```suggestion
        ArgumentNullException.ThrowIfNull(timeProvider);
        ArgumentNullException.ThrowIfNull(logger);

        _timeProvider = timeProvider;
        _logger = logger;
```

File: src/ReverseProxy/SessionAffinity/SessionAffinityMiddleware.cs [hunk 23]
```diff
@@ -29,10 +29,14 @@ public SessionAffinityMiddleware(
...
-        _sessionAffinityPolicies = sessionAffinityPolicies?.ToDictionaryByUniqueId(p => p.Name) ?? throw new ArgumentNullException(nameof(sessionAffinityPolicies));
-        _affinityFailurePolicies = affinityFailurePolicies?.ToDictionaryByUniqueId(p => p.Name) ?? throw new ArgumentNullException(nameof(affinityFailurePolicies));
+        ArgumentNullException.ThrowIfNull(next);
+        _next = next;
+        ArgumentNullException.ThrowIfNull(logger);
+        _logger = logger;
+        ArgumentNullException.ThrowIfNull(sessionAffinityPolicies);
+        ArgumentNullException.ThrowIfNull(affinityFailurePolicies);
+        _sessionAffinityPolicies = sessionAffinityPolicies.ToDictionaryByUniqueId(p => p.Name);
+        _affinityFailurePolicies = affinityFailurePolicies.ToDictionaryByUniqueId(p => p.Name);
```
Comment (MihaZupan) [inline src/ReverseProxy/SessionAffinity/SessionAffinityMiddleware.cs:39]:
```suggestion
        ArgumentNullException.ThrowIfNull(next);
        ArgumentNullException.ThrowIfNull(logger);
        ArgumentNullException.ThrowIfNull(sessionAffinityPolicies);
        ArgumentNullException.ThrowIfNull(affinityFailurePolicies);

        _next = next;
        _logger = logger;
        _sessionAffinityPolicies = sessionAffinityPolicies.ToDictionaryByUniqueId(p => p.Name);
        _affinityFailurePolicies = affinityFailurePolicies.ToDictionaryByUniqueId(p => p.Name);
```

File: src/ReverseProxy/Transforms/PathTransformExtensions.cs [hunk 24]
```diff
@@ -96,11 +87,7 @@ public static TransformBuilderContext AddPathRemovePrefix(this TransformBuilderC
     /// </summary>
     public static RouteConfig WithTransformPathRouteValues(this RouteConfig route, [StringSyntax("Route")] PathString pattern)
     {
-        if (pattern.Value is null)
-        {
-            throw new ArgumentNullException(nameof(pattern));
-        }
-
+        ArgumentNullException.ThrowIfNull(pattern.Value);
```
Comment (MihaZupan) [inline src/ReverseProxy/Transforms/PathTransformExtensions.cs:90]:
```suggestion
        ArgumentNullException.ThrowIfNull(pattern.Value);

```

File: src/ReverseProxy/WebSocketsTelemetry/HttpConnectFeatureWrapper.cs [hunk 25]
```diff
@@ -26,9 +26,12 @@ internal sealed class HttpConnectFeatureWrapper : IHttpExtendedConnectFeature
...
     {
-        _timeProvider = timeProvider ?? throw new ArgumentNullException(nameof(timeProvider));
-        HttpContext = httpContext ?? throw new ArgumentNullException(nameof(httpContext));
-        InnerConnectFeature = connectFeature ?? throw new ArgumentNullException(nameof(connectFeature));
+        ArgumentNullException.ThrowIfNull(timeProvider);
+        _timeProvider = timeProvider;
+        ArgumentNullException.ThrowIfNull(httpContext);
+        HttpContext = httpContext;
+        ArgumentNullException.ThrowIfNull(connectFeature);
+        InnerConnectFeature = connectFeature;
```
Comment (MihaZupan) [inline src/ReverseProxy/WebSocketsTelemetry/HttpConnectFeatureWrapper.cs:34]:
```suggestion
        ArgumentNullException.ThrowIfNull(timeProvider);
        ArgumentNullException.ThrowIfNull(httpContext);
        ArgumentNullException.ThrowIfNull(connectFeature);

        _timeProvider = timeProvider;
        HttpContext = httpContext;
        InnerConnectFeature = connectFeature;
```

File: src/ReverseProxy/WebSocketsTelemetry/HttpUpgradeFeatureWrapper.cs [hunk 26]
```diff
@@ -25,9 +25,12 @@ internal sealed class HttpUpgradeFeatureWrapper : IHttpUpgradeFeature
...
     {
-        _timeProvider = timeProvider ?? throw new ArgumentNullException(nameof(timeProvider));
-        HttpContext = httpContext ?? throw new ArgumentNullException(nameof(httpContext));
-        InnerUpgradeFeature = upgradeFeature ?? throw new ArgumentNullException(nameof(upgradeFeature));
+        ArgumentNullException.ThrowIfNull(timeProvider);
+        _timeProvider = timeProvider;
+        ArgumentNullException.ThrowIfNull(httpContext);
+        HttpContext = httpContext;
+        ArgumentNullException.ThrowIfNull(upgradeFeature);
+        InnerUpgradeFeature = upgradeFeature;
```
Comment (MihaZupan) [inline src/ReverseProxy/WebSocketsTelemetry/HttpUpgradeFeatureWrapper.cs:33]:
```suggestion
        ArgumentNullException.ThrowIfNull(timeProvider);
        ArgumentNullException.ThrowIfNull(httpContext);
        ArgumentNullException.ThrowIfNull(upgradeFeature);

        _timeProvider = timeProvider;
        HttpContext = httpContext;
        InnerUpgradeFeature = upgradeFeature;
```

File: src/TelemetryConsumption/EventListenerService.cs [hunk 27]
```diff
@@ -37,9 +37,11 @@ public EventListenerService(
...
         IEnumerable<IMetricsConsumer<TMetrics>> metricsConsumers)
     {
-        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
-        _ = telemetryConsumers ?? throw new ArgumentNullException(nameof(telemetryConsumers));
-        _ = metricsConsumers ?? throw new ArgumentNullException(nameof(metricsConsumers));
+        ArgumentNullException.ThrowIfNull(logger);
+        ArgumentNullException.ThrowIfNull(telemetryConsumers);
+        ArgumentNullException.ThrowIfNull(metricsConsumers);
+        
+        _logger = logger;
```
Comment (MihaZupan) [inline src/TelemetryConsumption/EventListenerService.cs:45]:
```suggestion
```

**Review by MihaZupan — APPROVED** [review]
Thanks

File: src/ReverseProxy/Management/ProxyConfigManager.cs (hunk 8 above)
Comment (WeihanLi) [reply src/ReverseProxy/Management/ProxyConfigManager.cs:90]: Do we need to update for filters also?

```cs
        _filters = (filters as IProxyConfigFilter[]) ?? filters.ToArray();
```

Comment (MihaZupan) [reply src/ReverseProxy/Management/ProxyConfigManager.cs:90]: Yes please

Comment (WeihanLi) [reply src/ReverseProxy/Management/ProxyConfigManager.cs:90]: And for the `configChangeListeners`, currently, there's no null check for it, seems we should add null check for it since it's not nullable from the signature?
